version: "3"
services:
  web:
    restart: always
    build: ./webserver
    container_name: "ee_web"
    command: ["bash","-c","sleep 2 && python main.py"]
    tty: true
    environment:
      MYSQL_USER: eeMySql1
      MYSQL_PASSWORD: eeMySql1
      MYSQL_HOST: db
      MYSQL_DB: eeproject
      API_BASE_URL: http://example.com
    volumes:
      - ./webserver:/root/opt
    ports:
      - 8080:8080
  api:
    restart: always
    build: ./apserver
    container_name: "ee_api"
    command: "python main.py"
    volumes:
      - ./apserver:/root/opt
    hostname: example.com
    ports:
      - 80:80
  db:
    build: ./dbserver
    container_name: ee_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eeproject
      MYSQL_USER: eeMySql1
      MYSQL_PASSWORD: eeMySql1
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
      - ./dbserver/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./dbserver/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
